//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 01:55:16 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://snva.com/xml/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.snva.xml.user;
