//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 06:01:04 PM EDT 
//


package com.snva.ex.soap.xml.bootcamp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bootcampName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bootcampName"
})
@XmlRootElement(name = "getBootcampRequest")
public class GetBootcampRequest {

    @XmlElement(required = true)
    protected String bootcampName;

    /**
     * Gets the value of the bootcampName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBootcampName() {
        return bootcampName;
    }

    /**
     * Sets the value of the bootcampName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBootcampName(String value) {
        this.bootcampName = value;
    }

}
