//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 06:01:04 PM EDT 
//


package com.snva.ex.soap.xml.bootcamp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Bootcamp" type="{http://snva.com/ex/soap/xml/bootcamp}Bootcamp"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bootcamp"
})
@XmlRootElement(name = "getBootcampResponse")
public class GetBootcampResponse {

    @XmlElement(name = "Bootcamp", required = true)
    protected Bootcamp bootcamp;

    /**
     * Gets the value of the bootcamp property.
     * 
     * @return
     *     possible object is
     *     {@link Bootcamp }
     *     
     */
    public Bootcamp getBootcamp() {
        return bootcamp;
    }

    /**
     * Sets the value of the bootcamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bootcamp }
     *     
     */
    public void setBootcamp(Bootcamp value) {
        this.bootcamp = value;
    }

}
