//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 06:01:04 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://snva.com/ex/soap/xml/bootcamp", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.snva.ex.soap.xml.bootcamp;
